---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: omv
    ansible_password: k4t4m4r1AA
  hosts:
    ilpalazzo:
      swap_file_size_mb: 2048
      config_settings:
        - name: "gpu_mem"
          value: 16
